export enum Names {
  'HR-HR' = 'HR Interview',
  'TECHNICAL-TECHNICAL' = 'Technical Interview',
  'OFFER-OFFER' = 'Your Ofer',
  'COGNITIVE-COG' = 'Cognitive Test',
  'COGNITIVE-COG#1' = 'Cognitive Test 1',
  'COGNITIVE-COG#2' = 'Cognitive Test 2',
  'COGNITIVE-COG#3' = 'Cognitive Test 3',
  'COGNITIVE-COG#4' = 'Cognitive Test 4',
  'ADMISSION-ADM' = 'Admission Test',
  'ADMISSION-ADM#QA' = 'Admission QA Test',
  'ADMISSION-ADM#JQA' = 'Admission JQA Test',
  'LANGUAGE-ENG' = 'English Test',
  'DUMMY-DUMMY' = 'Dummy Test',
  'SKILLS-undefined' = 'Skill Matrix',
  'PRACTICAL' = 'Practical Task',
  'COGNITIVE-COG#ES' = 'Cognitive Spanish Test',
  'LANGUAGE-ENG#2' = 'English Test 2',
  'LANGUAGE-ENG#3' = 'English Test 3',
}
